trigger:
- main

pool:
  name: gaurav
stages:
  - stage: Build
    jobs:
      - job: Buildpipeline
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module/'
            backendServiceArm: 'ServiceV3'
            backendAzureRmStorageAccountName: 'storageaccountnewgauravs'
            backendAzureRmContainerName: 'containergaurav'
            backendAzureRmKey: 'Terraformvar'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            environmentServiceNameAzureRM: 'ServiceV3'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
            environmentServiceNameAzureRM: 'ServiceV3'